{% set name = "ecdsa" %}
{% set version = "0.17.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b9f500bb439e4153d0330610f5d26baaf18d17b8ced1bc54410d189385ea68aa

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  host:
    - pip
    - python
  run:
    - python
    - six

test:
  imports:
    - ecdsa

about:
  home: http://github.com/warner/python-ecdsa
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: ECDSA cryptographic signature library (pure python)

extra:
  recipe-maintainers:
    - mariusvniekerk
