{% set name = "ecdsa" %}
{% set version = "0.19.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 60eaad1199659900dd0af521ed462b793bbdf867432b3948e87416ae4caf6bf8

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - python
    - six >=1.9.0

test:
  imports:
    - ecdsa
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tlsfuzzer/python-ecdsa
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: ECDSA cryptographic signature library (pure python)
  dev_url: https://github.com/tlsfuzzer/python-ecdsa
  doc_url: https://pypi.org/project/ecdsa

extra:
  recipe-maintainers:
    - mariusvniekerk
