travis:
  secure:
    BINSTAR_TOKEN: EWj24n+96y+zrCMnf9APYsV9FPsgOY0tsxNdzz/O6vn8TRCYvLQVXyBW2+NbdGA2rK6rRjEjza8ot+1DL/14hRUfytjbxzaA6JTgamj71l4jczwXSxW1m+epER+Ci/DjM27NllJsQxMuBHBww7NzIgSOv6PNdYwfh+kdl1wFhHHOAhopruC0+7mcwlQXZioh1IGstoch7X2YU9VaBGNb9yyqnv9rCdSD7JFz4aH6RMuzmsgSTR4cwyKCFE7JokhrmyI6ilhaUc7xjWGPZjdnhDmzUgXYMKS9xm+QBWF6DyBnlqJJJRfVf94tYUpnLuNAs3rhQpfAlwQMQM5Od66mx1ygFbxpKLaPGH6T1KrpiAbMtSGLNxx11doPbK2jD2RQPpgNNSmQkpOBllmtI0/m9B0WdqQGb5DjR2f1usJLxeNdfF2BA6WO4nN1gujEWZ9R/rqu0KA1EXW80tfT+NoCWBxNg5Coda7Aqzi7A5G3dV6eGUtQSvOARcTDUQGa7PBKyw+4xfORFzf80leTqrEVZZ+Adjn93IP7MnXsQQD0olYEvsLernoOwmpW+iddsTBWtVcb8KHiK+8j9ZDfln5N0KVBDE4blsqvcTq6p1gecZlW6oI4CaXooAiLm67i4IqXN/AQTJp2g8YD+pHN5kLPwsAgX/Jgbpn/G4kcghobPR0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
